<a href="https://colab.research.google.com/github/KKhandelwal1733/Machine-Learning/blob/main/emailspam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import nltk
from nltk.probability import FreqDist
import string
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier as RFR
from sklearn.metrics import accuracy_score

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [2]:
df=pd.read_csv('/content/drive/MyDrive/Datasets/spam.csv',encoding='latin-1')


In [3]:
df.columns
df[:10]


v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   
5  spam  FreeMsg Hey there darling it's been 3 week's n...        NaN   
6   ham  Even my brother is not like to speak with me. ...        NaN   
7   ham  As per your request 'Melle Melle (Oru Minnamin...        NaN   
8  spam  WINNER!! As a valued network customer you have...        NaN   
9  spam  Had your mobile 11 months or more? U R entitle...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN  
5        NaN        NaN  
6        NaN        NaN  
7        NaN        NaN  
8        NaN        NaN  
9        NaN        NaN

In [ ]:
df['v2']

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: v2, Length: 5572, dtype: object

In [4]:
ps = PorterStemmer()
corpus = []

all_stop_words = set(stopwords.words('english'))
all_stop_words.remove('not')

for i in range (len(df)):
    text = df['v2'][i].lower().translate(str.maketrans('','', string.punctuation)).split()
    text = [ps.stem(word) for word in text if word not in all_stop_words]
    text = ' '.join(text)
    corpus.append(text)
#print(corpus)

In [ ]:
cv = CountVectorizer()
X = cv.fit_transform(corpus).toarray()
y = df['v1']



In [ ]:
print(X)
len(X[0])

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


8039

In [ ]:
flat_filtered =" ".join(corpus).split()
# getting frequency distribution
clean_corpus_freqdist = FreqDist(flat_filtered)
# top 20 words in cleaned corpus
clean_corpus_freqdist.most_common(20)

[('u', 1119),
 ('call', 653),
 ('2', 478),
 ('im', 463),
 ('go', 449),
 ('get', 447),
 ('not', 430),
 ('ur', 384),
 ('come', 297),
 ('4', 287),
 ('dont', 279),
 ('ok', 277),
 ('ltgt', 276),
 ('free', 275),
 ('know', 270),
 ('like', 255),
 ('love', 244),
 ('want', 243),
 ('day', 241),
 ('ill', 239)]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)


In [ ]:
len(X_test)

1672

In [ ]:
km=RFR()
km.fit(X_train,y_train)
y_pred=km.predict(X_test)
accuracy_score(y_pred,y_test)


0.9647129186602871

In [ ]:
dict={0:'ham',
      1:'spam'}
km.score(X_train,y_train)


1.0

In [ ]:
ll=[  y_pred[:30]],[  y_test[:30]]
arr=np.array(ll)

arr.reshape

print(arr)






[[['ham' 'ham' 'ham' 'ham' 'ham' 'ham' 'ham' 'ham' 'ham' 'ham' 'ham'
   'ham' 'ham' 'spam' 'ham' 'ham' 'spam' 'ham' 'ham' 'ham' 'ham' 'ham'
   'ham' 'ham' 'ham' 'ham' 'spam' 'ham' 'ham' 'ham']]

 [['ham' 'ham' 'ham' 'ham' 'ham' 'ham' 'ham' 'ham' 'ham' 'spam' 'ham'
   'ham' 'ham' 'spam' 'ham' 'ham' 'spam' 'ham' 'ham' 'ham' 'ham' 'ham'
   'ham' 'ham' 'spam' 'ham' 'spam' 'ham' 'spam' 'ham']]]


In [ ]:
"""mess=["Dear Customer, You have a missed call from +918440005608 The last missed call was at 04:15 PM on 01-Jan-2024 Thankyou, Team Jio."]










for i in range (len(z)):
    text = df['v2'][i].lower().translate(str.maketrans('','', string.punctuation)).split()
    text = [ps.stem(word) for word in text if word not in all_stop_words]
    text = ' '.join(text)
    corpus.append(text)
count=0
for i in z[0]:
  if i == 1:
   count=count+1
print(count)

predicted=km.predict(z)

print(z,predicted)"""

NameError: name 'z' is not defined